In [ ]:
"""Theoretical Questions"""

In [ ]:
""""
Q1)  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for 
     numerical operations?
Answer-
     NumPy (Numerical Python) is a powerful library for scientific computing and data analysis in Python. 
     Here's how NumPy enhances Python's capabilities for numerical operations and why it's widely used in scientific computing and data 
     analysis:
     1) Efficient Arrays - 
        Purpose: NumPy introduces the ndarray, a powerful object for creating and handling multi-dimensional arrays 
        (lists of numbers arranged in rows and columns, like spreadsheets).
        Advantage: These arrays are faster and take up less memory than Python's regular lists, especially when working with large datasets.
     2) Fast Calculations -
        Purpose: NumPy allows you to perform math operations (like adding, multiplying, etc.) on entire arrays at once, without needing loops.
        Advantage: This makes your code much faster because NumPy is optimized using C code under the hood, which runs quicker than regular 
        Python loops.
     3) Memory Efficiency -
        Purpose: NumPy arrays store data more compactly than Python lists by using fixed data types.
        Advantage: This helps save memory, especially when working with big data, and improves performance.
     4) Math Functions -
        Purpose: NumPy provides a wide range of built-in functions for performing math operations, such as statistics, linear algebra, and 
        random number generation.
        Advantage: You get access to ready-made tools for complex calculations, saving time and effort.
     5) Works with Other Libraries -
        Purpose: Many popular Python libraries (like Pandas, SciPy, and TensorFlow) use NumPy arrays.
        Advantage: This makes it easier to work with different libraries together, as they share a common data structure.
     6. Broadcasting -
        Purpose: NumPy allows you to perform operations on arrays of different sizes without needing to reshape them manually.
        Advantage: This simplifies calculations and saves time when working with arrays of varying dimensions.
     7. Data Handling -
        Purpose: NumPy makes it easy to reshape, slice, and manipulate arrays.
        Advantage: You can quickly modify your data to fit the format you need, making it easier to clean and prepare data for analysis.
     8. Widely Used and Open Source -
        Purpose: NumPy is free and widely supported by a large community.
        Advantage: You can find plenty of resources, tutorials, and help online, making it easier to learn and use.
    
     NumPy improves Python by making numerical operations faster and more memory-efficient. It allows you to handle large datasets and perform
     complex calculations with ease, making it an essential tool for scientific computing, data analysis, and machine learning.
"""

In [ ]:
"""
Q2) Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
Answer-
    In NumPy, both np.mean() and np.average() are used to calculate the average of an array, but there are key differences between them in 
    terms of functionality and use cases. Here’s a comparison and explanation of when to use one over the other -
    1) Basic Functionality -
       np.mean(): This function computes the arithmetic mean (or simple average) of the elements in an array.
       np.average(): By default, this function also computes the arithmetic mean, but it allows you to include weights, which means you can 
       compute a weighted average.
    2) Weights Parameter -
       np.mean(): Does not support weights. It calculates a simple average without considering any importance or weight of individual
       elements.
       np.average(): Supports a weights parameter that allows you to assign different weights to elements, making it ideal for calculating 
       weighted averages.
    3) Return Value -
       np.mean(): Returns a single scalar value representing the arithmetic mean of all elements.
       np.average(): Also returns a scalar when computing the average. However, if you provide weights and specify returned=True, it will 
       return a tuple containing the average and the sum of the weights.
    4) Performance -
       np.mean(): Generally faster when you only need a simple average since it doesn’t involve the additional overhead of processing weights.
       np.average(): Slightly slower due to the flexibility it offers with weights, even if weights are not used.
    5) Use Cases -
       Use np.mean() when:
       a) You want to compute a simple arithmetic mean of an array.
       b) You do not need to consider the importance or weight of individual elements.
       c) You are looking for a fast, straightforward average calculation.
      Use np.average() when:
       a) You need to calculate a weighted average where some elements contribute more to the result than others.
       b) You want to retrieve both the average and the sum of the weights using the returned=True option.
"""

In [5]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.6 MB 6.3 MB/s eta 0:00:02
   ----- ---------------------------------- 1.8/12.6 MB 4.6 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 4.3 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.6 MB 4.3 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 4.2 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 4.1 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.6 MB 4.1 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.6 MB 4.1 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.6 MB 4.0 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.6 MB 4.0 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.6 MB 4.0 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 4.0 MB/s eta 0:00:01
   --

In [2]:
# Example of When to Use Each:
#Use np.mean(): If you have an array of student grades and you want the overall average score:
import numpy as np
scores = np.array([85, 90, 88, 92])
print(np.mean(scores))  


88.75


In [3]:
#Use np.average(): If you want to calculate a student's weighted average score, where different subjects have different importance
scores = np.array([85, 90, 88, 92])  
weights = np.array([0.4, 0.3, 0.2, 0.1])  
print(np.average(scores, weights=weights))  


87.80000000000001


In [ ]:
"""
Q3) Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
Answer-
    Reversing a NumPy array can be done in several ways depending on the array's dimensions and the axes along which you want to reverse it. 
    Here are some methods for reversing NumPy arrays along different axes:
    1) Reversing a 1D Array -
       For a 1D array (a simple list of numbers), you can reverse it using slicing.
       Method: Slicing ([::-1])
       You can reverse a 1D array by slicing it with the step -1, which effectively reverses the order of the elements.
    2) Reversing a 2D Array -
       For 2D arrays (matrices), you can reverse the array along different axes: rows, columns, or both.
       a) Method 1: Reversing Rows-
          To reverse the rows of a 2D array, use slicing with [::-1, :]. This will reverse the order of the rows while keeping the columns
          intact.
       b) Method 2: Reversing Columns-
          To reverse the columns of a 2D array, use slicing with [:, ::-1]. This will reverse the order of the columns while keeping the rows
          intact.
       c) Method 3: Reversing Both Rows and Columns -
          To reverse both rows and columns, combine the slicing approaches: [::-1, ::-1].
    3) Using np.flip() -
       np.flip() is a NumPy function specifically designed to reverse the elements of an array along a specified axis. You can use this method
       for any dimension (1D, 2D, etc.)
       Syntax-  np.flip(array, axis)
       axis=0: Reverses the array along rows.
       axis=1: Reverses the array along columns.
       
"""

In [4]:
#Example 1: Reversing a 1D array using np.flip()
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = np.flip(arr)
print(reversed_arr)  


[5 4 3 2 1]


In [5]:
#Example 2: Reversing a 2D array using np.flip() along rows
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

flipped_rows = np.flip(arr_2d, axis=0)
print(flipped_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [6]:
#Example 3: Reversing a 2D array using np.flip() along columns
flipped_columns = np.flip(arr_2d, axis=1)
print(flipped_columns)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [7]:
#Example 4: Reversing a 1D Array
arr = np.array([1, 2, 3, 4, 5])

reversed_arr = arr[::-1]
print(reversed_arr)  

[5 4 3 2 1]


In [8]:
#Example 5: Reversing a 2D Array
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

reversed_rows = arr_2d[::-1, :]
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:

"""
Q4) How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and 
    performance.
Answer- 
    Importance of Data Types in Memory Management and Performance
    1) Memory Management:
       a) NumPy arrays are stored as contiguous blocks of memory, which makes accessing elements more efficient than lists. Each element in a 
       NumPy array has a fixed size, determined by its data type.
       b) Using appropriate data types reduces memory consumption. For instance, storing integers as int8 (8-bit integers) uses less memory than
       int64 (64-bit integers). Choosing the right data type for your data can significantly reduce the memory footprint of large arrays.

    2) Performance:
       a) Data types affect computational performance. Smaller data types (e.g., float32, int16) can be processed faster than larger types
          (e.g., float64, int64) because they require less memory bandwidth and cache usage.
       b) NumPy operations are optimized to run efficiently on fixed-size data types, leveraging CPU vectorization (SIMD operations) for 
          performance improvements.    

    3) Precision:
       a) Data types also impact the precision of computations. For example, float32 offers less precision than float64. Depending on the 
          requirements, you should select a data type that offers sufficient precision without wasting resources.   

"""

In [11]:
#To determine the data type of elements in a NumPy array, we use the dtype attribute. 
#checking the data type of elements in a NumPy array

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [13]:
#In this example arr_int8 Uses 1 byte per element, arr_int64 Uses 8 bytes per element

arr_int8 = np.array([1, 2, 3], dtype=np.int8)  
arr_int64 = np.array([1, 2, 3], dtype=np.int64) 
print(arr_int8.nbytes)  
print(arr_int64.nbytes) 

3
24


In [ ]:
"""
Q5) Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
Answer-
    An ndarray (N-dimensional array) in NumPy is a grid of values, all of the same type, indexed by a tuple of non-negative integers. It is 
    the core data structure of the NumPy library, allowing efficient storage and manipulation of large amounts of data in a structured, 
    multi-dimensional format.
    Key Features of ndarray -
    1) Homogeneous Data Types: 
       All elements in an ndarray must have the same data type (e.g., integers, floats). This allows for efficient memory allocation and 
       computation.
    2) N-dimensional: 
       Unlike a standard Python list, which is essentially one-dimensional, ndarray can be multi-dimensional (1D, 2D, 3D, etc.).
    3) Efficient Memory Management: 
       Since ndarray stores data in a contiguous block of memory, it minimizes memory overhead and allows efficient computation, especially 
       with large datasets.
    4) Vectorized Operations:
       NumPy supports element-wise operations without needing explicit loops, making mathematical and logical operations more concise and 
       much faster.
    5) Broadcasting: 
       NumPy arrays support broadcasting, which allows arithmetic operations between arrays of different shapes, by automatically expanding 
       the smaller array.
    6) Shape and Size Flexibility: 
       You can reshape, slice, and index ndarray objects easily, making it versatile for various computational tasks.
    7) Built-in Mathematical Functions: 
       NumPy provides numerous optimized mathematical and statistical functions like mean(), sum(), dot(), and max() that work directly on 
       arrays. 

    Differences between ndarray and Python Lists:
    1) Data Type:
       ndarray(Numpy) - Homogeneous (all elements have the same type)	
       Python List - Heterogeneous (can store mixed types)
    2) Dimensionality:
       ndarray(Numpy) - Multi-dimensional (1D, 2D, nD)	
       Python List - Mostly 1D (nested lists simulate higher dimensions)
    3) Memory Efficiency:   
       ndarray(Numpy) - Stored in contiguous memory blocks, efficient	
       Python List - Less efficient due to memory overhead
    4) Operations:
       ndarray(Numpy) - Supports fast, element-wise operations	
       Python List - Operations often require explicit loops
    5) Broadcasting:   
       ndarray(Numpy) - Supports broadcasting for element-wise operations with different shapes
       Python List - Not supported
    6) Performance:
       ndarray(Numpy) - Highly optimized for numerical computations	
       Python List - Slower for large datasets
    7) Built-in Functions:
       ndarray(Numpy) - Rich set of mathematical functions	
       Python List - Fewer built-in math-related functions
    8) Reshaping:
       ndarray(Numpy) - Can easily reshape without copying data	
       Python List - Reshaping requires manually creating new lists
"""

In [4]:
#Key Features of ndarray
#Homogeneous Data Types
arr = np.array([1,2,3,4])
print(type(arr))
print(arr.dtype)
# All elements are of type float32

<class 'numpy.ndarray'>
int64


In [8]:
#N-dimensional
# 2D array
arr_2d = np.array([[1, 2], [3, 4]])  
arr_2d.ndim

2

In [10]:
#Vectorized Operations
# Element-wise multiplication
arr = np.array([1, 2, 3])
result = arr * 2 
print(result) 

[2 4 6]


In [11]:
#Broadcasting
# Adds 5 to every element
arr = np.array([1, 2, 3])
result = arr + 5  
print(result)


[6 7 8]


In [12]:
#Shape and Size Flexibility
# Converts 1D array to 2D array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))  
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
"""
Q6) Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
Answer-
    The performance benefits of NumPy arrays over Python lists for large-scale numerical operations can be summarized as follows:

    1) Memory Efficiency:
       NumPy Arrays - Store elements in a contiguous block of memory with a fixed data type, making memory usage more efficient.
       Python Lists - Store references to objects, causing higher memory overhead, especially for large datasets.
    2) Speed (Vectorized Operations):
       NumPy Arrays - Support vectorized operations, meaning element-wise operations are performed in highly optimized C code, making them 
       much faster.
       Python Lists - Require explicit loops for element-wise operations, which are slower due to Python's interpreted nature.
    3) Broadcasting:
       NumPy Arrays - Allow arithmetic operations between arrays of different shapes without the need for loops, thanks to broadcasting.
       Python Lists - Do not support broadcasting, and manual handling (e.g., nested loops) is needed.
    4) Built-in Mathematical Functions:
       NumPy Arrays - Provide many optimized mathematical functions like sum(), mean(), and dot(), which are faster and more efficient.
       Python Lists - Use slower Python functions or require custom logic for numerical operations.
    5) Parallelization and Optimized CPU Use:
       NumPy Arrays - Take advantage of hardware-level optimizations such as SIMD (Single Instruction, Multiple Data), which further speeds 
       up large-scale operations.
       Python Lists - Do not leverage these optimizations, resulting in slower computations.
"""

In [4]:
#Memory Efficiency
import numpy as np
import sys

# Python list memory usage
python_list = [1,2,3,4,5]
print("Memory size of Python list:", sys.getsizeof(python_list))

# NumPy array memory usage
numpy_array = np.array([1,2,3,4,5])
print("Memory size of NumPy array:", numpy_array.nbytes)

Memory size of Python list: 104
Memory size of NumPy array: 40


In [14]:
#Speed and Vectorization
#Element-wise addition

import time

# Using Python list
python_list = list(range(2000000))
start = time.time()
python_result = (x * 2 for x in python_list)
print("Python list time:", time.time() - start)


# Using NumPy array
numpy_array = np.arange(2000000)
start = time.time()
numpy_result = (numpy_array * 2)
print("Numpy array time:", time.time() - start)


Python list time: 0.027103900909423828
Numpy array time: 0.006905317306518555


In [ ]:
"""
Q7)  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
Answer-
    In NumPy, the vstack() and hstack() functions are used to stack arrays together along different axes.

    1) vstack() (Vertical Stack):
       Function: Stacks arrays vertically (row-wise), meaning it combines arrays by adding more rows.
       Axis: It stacks arrays along the first axis (axis=0).
       Shape Requirement: Arrays must have the same number of columns.

    2) hstack() (Horizontal Stack)
       Function: Stacks arrays horizontally (column-wise), meaning it combines arrays by adding more columns.
       Axis: It stacks arrays along the second axis (axis=1) if they are 2D.
       Shape Requirement: Arrays must have the same number of rows.      
"""

In [17]:
#vstack()
# Two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_vstack = np.vstack((arr1, arr2))
print("Vertical Stack:\n", result_vstack)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [18]:
#hstack
# Two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_hstack = np.hstack((arr1, arr2))
print("Horizontal Stack:\n", result_hstack)


Horizontal Stack:
 [1 2 3 4 5 6]


In [20]:
#stacking 2D array
# Two 2D arrays
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])

result_vstack_2d = np.vstack((arr1_2d, arr2_2d))
print("Vertical Stack 2D:\n", result_vstack_2d)

result_hstack_2d = np.hstack((arr1_2d, arr2_2d))
print("Horizontal Stack 2D:\n", result_hstack_2d)


Vertical Stack 2D:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack 2D:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
"""
Q8) Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
Answer-
    In NumPy, fliplr() and flipud() are two methods used to flip or reverse the order of elements in a 2D array (or higher-dimensional arrays). They are specifically designed to flip the array along different axes:

    1) fliplr() (Flip Left to Right) -
       Function: Flips the array horizontally, reversing the order of columns (left to right).
       Effect: It flips the array along the second axis (axis=1).
       Applicable to: At least 2D arrays. For higher-dimensional arrays, it flips the elements in each 2D subarray along the second axis.

    2) flipud() (Flip Up to Down)
       Function: Flips the array vertically, reversing the order of rows (up to down).
       Effect: It flips the array along the first axis (axis=0).
       Applicable to: At least 2D arrays. For higher-dimensional arrays, it flips the elements in each 2D subarray along the first axis.
"""

In [23]:
# Flip left to right
# 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

result_fliplr = np.fliplr(arr)
print("Original Array:\n", arr)
print("fliplr (Left to Right Flip):\n", result_fliplr)


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
fliplr (Left to Right Flip):
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [24]:
# Flip up to down
result_flipud = np.flipud(arr)
print("flipud (Up to Down Flip):\n", result_flipud)


flipud (Up to Down Flip):
 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
"""
Q9) Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
Answer-
    The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is more flexible than the regular split() method
    because it can handle cases where the array cannot be evenly divided.

    Functionality:
    1) The array_split() method divides an array into a specified number of equally or unequally sized sub-arrays.
    2) If the array can't be divided evenly, it allows uneven splits by distributing the leftover elements into the earlier sub-arrays.

    Syntax:
    numpy.array_split(array, sections)
    where, array is the input array to be split and sections is the number of sub-arrays or a list of indices indicating where to split the 
    array.
    
    How it Handles Uneven Splits -
    When the array size is not evenly divisible by the number of sections specified, array_split() divides the array as evenly as possible,
    giving larger sub-arrays at the start. If some leftover elements remain, the first few sub-arrays get one extra element each until all 
    elements are distributed.

    Splitting 2D Arrays:
    array_split() can also split multi-dimensional arrays along a specific axis.

    Handling Uneven Splits in Multi-dimensional Arrays:
    If the number of rows (or columns, depending on the axis) is not evenly divisible, array_split() will distribute the extra rows/columns 
    into earlier sub-arrays.

    Key Differences from split():
    The split() function raises a ValueError if the array cannot be split evenly.
    The array_split() method handles uneven splits gracefully by adjusting the sub-array sizes.
"""

In [27]:
#solitting 1 D array into 3 subarrays
arr = np.array([1,2,3,4,5,6,7])
result = np.array_split(arr, 3)
print("Array split int 3 sunarrays:\n", result)

Array split int 3 sunarrays:
 [array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [29]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Splitting the array into 2 parts along the default axis (rows)
result_2d = np.array_split(arr_2d, 2)
print("2D Array Split into 2 sub-arrays:\n", result_2d)


2D Array Split into 2 sub-arrays:
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


In [30]:
#splitting into 4 parts using array_split()
arr = np.array([1,2,3,4,5,6,7])
result_uneven = np.array_split(arr, 4)
print("Uneven Split into 4 sub-arrays:\n", result_uneven)


Uneven Split into 4 sub-arrays:
 [array([1, 2]), array([3, 4]), array([5, 6]), array([7])]


In [ ]:
"""
Q10) Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
Answer-
    1) Vectorization in NumPy -
       Vectorization refers to the process of applying operations to entire arrays (or vectors) in a single step, without using explicit loops.
       In NumPy, this means that operations like addition, multiplication, and other element-wise operations are executed on the entire array
       at once. NumPy internally implements these operations in optimized C code, allowing them to run much faster than if you manually looped
       through each element in Python.
       Vectorization applies operations to entire arrays at once, improving speed and performance.

    Benefits of Vectorization:
    1) Speed: Vectorized operations are much faster than loops in Python because they eliminate the overhead of Python's interpreted loop 
       execution and leverage optimized low-level implementations.
    2) Cleaner Code: Vectorized operations make the code more concise and easier to read, as the same operation is applied to an entire array
       without needing explicit loops.

    2. Broadcasting in NumPy -
       Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes, by automatically "stretching" the 
       smaller array to match the shape of the larger array. This avoids the need to manually reshape arrays or repeat values, allowing for 
       efficient operations.
       Broadcasting allows arrays of different shapes to be operated on together by automatically expanding the smaller array to match the 
       shape of the larger array.

    How Broadcasting Works:
    When performing operations on arrays of different shapes, NumPy compares the shapes element-wise from right to left. If the dimensions 
    are not the same, NumPy:
    1) Tries to "broadcast" the smaller array by virtually replicating its data along the missing dimensions.
    2) It doesn’t actually copy data, which would be inefficient, but instead performs operations as if the smaller array were expanded.
    
    Rules for Broadcasting:
    1) If the dimensions are equal, the arrays are compatible.
    2) If one of the arrays has a dimension of size 1, NumPy "stretches" this dimension to match the other array.
    3) Arrays with incompatible shapes will raise a ValueError.

    contribution of Vectorization and Broadcasting to efficient array operations -
    1) Avoid Loops: Both vectorization and broadcasting eliminate the need for explicit Python loops, which are slow due to Python’s 
       interpreted nature. Instead, operations are performed using highly optimized, low-level code.

    2) Speed and Performance: 
       Vectorized operations are faster because NumPy leverages efficient C-based implementations that work on entire arrays at once.
       Broadcasting allows operations on arrays of different shapes without needing to manually reshape or copy data, saving both time and 
       memory.
    
    3) Memory Efficiency:
       Broadcasting avoids the need to create large temporary arrays (like repeated copies of smaller arrays), which would consume memory and
       slow down computations.
       NumPy handles array operations in-place wherever possible, further improving memory efficiency.

"""

In [31]:
#Example of Vectorization:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vectorized addition
result = arr1 + arr2  
print(result) 

#Instead of using a loop to add each element, NumPy performs the addition on the entire array in one step. This is not only faster but also
#more readable.

[5 7 9]


In [32]:
#Example of Broadcasting

arr1 = np.array([1, 2, 3])

arr2 = np.array([[4, 5, 6],
                 [7, 8, 9]])

result = arr1 + arr2
print(result)

# Broadcasting adds arr1 to each row of arr2


[[ 5  7  9]
 [ 8 10 12]]


In [ ]:
"""Practical Questions"""

In [46]:
"""
Q1) Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
Answer-
"""
numpy_array = np.random.randint(1,101, size =(3,3))
print("Original array:\n", numpy_array)

# Interchanging rows and columns (Transpose)
transposed_array = np.transpose(numpy_array)
print("\n Transposed array (rows and columns interchanged:)\n", transposed_array )

Original array:
 [[46 77 83]
 [75 77 64]
 [70 66 92]]

 Transposed array (rows and columns interchanged:)
 [[46 75 70]
 [77 77 66]
 [83 64 92]]


In [59]:
"""
Q2) Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
Answer-
"""
arr1 = np.arange(10)
print("1D array:\n", arr1)

arr1_2x5 = arr1.reshape(2, 5)
print("\n Reshaped to 2x5 Array:\n", arr1_2x5)

arr1_5x2 = arr1.reshape(5, 2)
print("\n Reshaped to 5x2 Array:\n", arr1_5x2)

1D array:
 [0 1 2 3 4 5 6 7 8 9]

 Reshaped to 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

 Reshaped to 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [78]:
"""
Q3) Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
Answer-
"""
arr_4x4 = np.random.rand(4, 4)
print(arr_4x4)

arr_6x6 = np.pad(arr_4x4, pad_width = 1, mode = 'constant', constant_values = 0)
print('\n',(arr_6x6))

#np.random.rand(4, 4) creates a 4x4 array of random floating-point numbers between 0 and 1.
#np.pad() adds a border of zeros around the original array, resulting in a 6x6 array.

[[0.42982357 0.27368008 0.09117126 0.89828537]
 [0.325883   0.5436922  0.69953075 0.71949257]
 [0.41868666 0.57041104 0.94513073 0.05322348]
 [0.25340399 0.47568095 0.67446781 0.80895121]]

 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.42982357 0.27368008 0.09117126 0.89828537 0.        ]
 [0.         0.325883   0.5436922  0.69953075 0.71949257 0.        ]
 [0.         0.41868666 0.57041104 0.94513073 0.05322348 0.        ]
 [0.         0.25340399 0.47568095 0.67446781 0.80895121 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [80]:
"""
Q4) Using NumPy, create an array of integers from 10 to 60 with a step of 5.
Answer-
"""
int_array = np.arange(10, 61, 5)
print(int_array)

[10 15 20 25 30 35 40 45 50 55 60]


In [96]:
"""
Q5) Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
    (uppercase, lowercase, title case, etc.) to each element.
Answer-
"""
str_array = np.array(['python', 'numpy', 'pandas'])
print('Array of strings:', str_array)

print('\n Uppercase:', np.char.upper(str_array))
print('\n Lowercase:', np.char.lower(str_array))
print('\n Title case:', np.char.title(str_array))

Array of strings: ['python' 'numpy' 'pandas']

 Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']

 Lowercase: ['python' 'numpy' 'pandas']

 Title case: ['Python' 'Numpy' 'Pandas']


In [98]:
"""
Q6) Generate a NumPy array of words. Insert a space between each character of every word in the array.
Answer-
"""
arr_words = np.array(['python', 'numpy', 'pandas'])
spaced_arr_words = np.char.join(' ', arr_words)
print(arr_words)
print(spaced_arr_words)


['python' 'numpy' 'pandas']
['p y t h o n' 'n u m p y' 'p a n d a s']


In [118]:
"""
Q7) Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
Answer-
"""

arr1_2D = np.array([[5,27,3,4]])
arr2_2D = np.array([[6,17,7,8]])

Addition = np.add(arr1_2D, arr2_2D)
print('Addition: ', Addition)

Subtraction = np.subtract(arr1_2D, arr2_2D)
print('Subtraction: ', Subtraction)

Multiplication = np.multiply(arr1_2D , arr2_2D)
print('Multiplication: ', Multiplication)

Division = np.divide(arr1_2D , arr2_2D)
print('Division: ', Division)


Addition:  [[11 44 10 12]]
Subtraction:  [[-1 10 -4 -4]]
Multiplication:  [[ 30 459  21  32]]
Division:  [[0.83333333 1.58823529 0.42857143 0.5       ]]


In [122]:
"""
Q8) Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
Answer-
"""
identity_matrix = np.eye(5)
print('5x5 identity matrix:\n', identity_matrix)

diagonal_el = np.diag(identity_matrix)
print('\n Diagonal elements: \n', diagonal_el)

5x5 identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 Diagonal elements: 
 [1. 1. 1. 1. 1.]


In [132]:
"""
Q9) Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
Answer-
"""
random_int = np.random.randint(0, 1000, size = 100)
print('Random integers between 0 to 1000: \n', random_int)

def is_prime(number):
    if number < 2:
        return False
    for i in range(2, int(np.sqrt(number)) + 1):
        if number % i == 0:
            return False
        return True
prime_numbers = np.array([number for number in random_int if is_prime(number)])  
print('\n Prime numbers in the array: \n', prime_numbers)

Random integers between 0 to 1000: 
 [569 338 755 280 372 548 262 375 129  65 475 922 152 363 279 279 197 272
 761 401 595 563 861  46 470 620  41 524 208  67 371 251 630 201 889 773
 696  58 469 881 698 513 318 118 347 127 933  60 998 449 643 935 889 206
  56 844 163 887 149 891 340 520 326 214   1 431 194 141 274  12 783 517
 436 801   6 457 707 285 749 427 191 208 555 850 804 994 178  31 206 246
 654 906 274 591 475  11  53 155 804 437]

 Prime numbers in the array: 
 [569 755 375 129  65 475 363 279 279 197 761 401 595 563 861  41  67 371
 251 201 889 773 469 881 513 347 127 933 449 643 935 889 163 887 149 891
 431 141 783 517 801 457 707 285 749 427 191 555  31 591 475  11  53 155
 437]


In [156]:
"""
Q10) Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages. 
Answer-
"""
#Assuming a month has 30 days
daily_temperature = np.random.randint(15, 36, size = 30)
print('Daily temperature: \n',daily_temperature)

weeks = np.split(daily_temperature[:28], 4)

weekly_avg = np.array([np.mean(week) for week in weeks])
print('\nWeekly Average:\n', weekly_avg)

last_2days = np.mean(daily_temperature[28:])
print(f'\nAverage for last 2 days:\n {last_2days}°C')

Daily temperature: 
 [19 28 32 20 31 32 24 30 20 34 17 31 19 23 25 19 15 18 33 34 33 15 20 23
 30 18 22 25 31 15]

Weekly Average:
 [26.57142857 24.85714286 25.28571429 21.85714286]

Average for last 2 days:
 23.0°C
